### ISSUE TITLE
add morgan for logging

### ISSUE THREAD

**Issue by reggieroby** [reggieroby/travel_hive#28]
should wrap console.logs with a higher level module "logger" and import the logger module into files.
using: https://github.com/expressjs/morgan as the underlying logger. 

for example:
    main.js
`
import {logger} from '../../utils/logger'
logger({event,thing,date,data},level);
`
    logger.js
`
import morgan from 'morgan'
....//something like
 function(args,level){ morgan[level](...args)}
`

that might be a LOT to grep. but we can talk about it.

**Comment by jvaughn575** [comment]
Can morgan be used for client-side and server side logging or just server side?

**Comment by reggieroby** [comment]
it would appear that morgan is a server side logger.

**Comment by jvaughn575** [comment]
Time: 
 research: 1hr
 implement: 1hr
